# Generated by Django 2.0.4 on 2018-05-09 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('font_class', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_day', models.DateField()),
                ('available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_amount', models.FloatField(null=True)),
                ('num_guests', models.IntegerField(null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('is_cancelled', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.TextField(max_length=50)),
                ('privacy_type', models.TextField(max_length=10)),
                ('bedroom', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('bed', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('city', models.TextField(blank=True, max_length=100)),
                ('country', models.TextField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('price', models.FloatField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('addr_lat', models.FloatField(null=True)),
                ('addr_lon', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(to='airbnbclone.Amenity')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_in_convo', to='airbnbclone.Conversation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=64, null=True)),
                ('description', models.CharField(default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_listings', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='home_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='airbnbclone.Listing'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_conversations', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_conversations', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo_about', to='airbnbclone.Listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_bookings', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='booking',
            name='home_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_guests', to='airbnbclone.Listing'),
        ),
        migrations.AddField(
            model_name='availability',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_availability', to='airbnbclone.Listing'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('guest', 'home_listing')},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('listing', 'one_day')},
        ),
    ]
