# Generated by Django 2.0.4 on 2018-05-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='has_listings', to='airbnbclone.User'),
        ),
    ]
