# Generated by Django 2.0.4 on 2018-05-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
