# Generated by Django 2.0.4 on 2018-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0002_auto_20180507_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(null=True, to='airbnbclone.Amenity'),
        ),
    ]
