# Generated by Django 2.0.4 on 2018-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0003_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='charge_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(to='airbnbclone.Amenity'),
        ),
    ]
