# Generated by Django 2.0.4 on 2018-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_primary',
            field=models.IntegerField(null=True),
        ),
    ]
