# Generated by Django 2.0.4 on 2018-05-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0005_photo_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='is_primary',
            field=models.BooleanField(),
        ),
    ]
