# Generated by Django 2.0.4 on 2018-05-08 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='guest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='guest_messaging', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='host_messaging', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='convo_about', to='airbnbclone.Listing'),
        ),
    ]
