# Generated by Django 2.0.4 on 2018-05-10 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0006_auto_20180510_0337'),
        ('airbnbclone', '0006_auto_20180510_0137'),
    ]

    operations = [
    ]
