# Generated by Django 2.0.4 on 2018-05-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0007_auto_20180508_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='message',
            name='host',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receives_message', to='airbnbclone.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sends_message', to='airbnbclone.User'),
        ),
    ]
