# Generated by Django 2.0.4 on 2018-05-10 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0007_merge_20180510_0516'),
        ('airbnbclone', '0007_merge_20180510_0743'),
    ]

    operations = [
    ]
