# Generated by Django 2.0.4 on 2018-05-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0008_merge_20180510_0800'),
        ('airbnbclone', '0008_merge_20180510_0757'),
    ]

    operations = [
    ]
