# Generated by Django 2.0.4 on 2018-05-08 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0008_auto_20180508_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='airbnbclone.User')),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='guests',
            new_name='num_guests',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='num_guests',
            new_name='max_guests',
        ),
        migrations.AddField(
            model_name='favorite',
            name='home_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='airbnbclone.Listing'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('guest', 'home_listing')},
        ),
    ]
