# Generated by Django 2.0.4 on 2018-05-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0009_auto_20180508_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='addr_lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='addr_lon',
            field=models.FloatField(null=True),
        ),
    ]
