# Generated by Django 2.0.4 on 2018-05-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnbclone', '0010_auto_20180508_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='one_day',
            field=models.DateField(),
        ),
    ]
